---
title: "Course Calendar"
---

+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| Lecture | Date    | Topics                                                  | Textbook                                                                                    | Materials                                                                                         | Homework                                                                                                                     |
+=========+=========+=========================================================+=============================================================================================+===================================================================================================+==============================================================================================================================+
| 1       | 8/28    | Course introduction, linear algebra and calculus review | [Book 1](https://probml.github.io/pml-book/book1.html): 7.1.1-7.2.4, 7.8.1, 7.8.2           | [Notes](../lecture1-background/notes.qmd)                                                         | Homework 1 assigned ([Github](https://github.com/orgs/CS152-Neural-Networks-Fall-2023/repositories)) **Due: 9/5 11:59pm**    |
|         |         |                                                         |                                                                                             |                                                                                                   |                                                                                                                              |
|         |         |                                                         |                                                                                             | [Slides](../lecture1-background/slides.qmd)                                                       | [Solutions](../assignments/homework1-background/solutions.html)                                                              |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 2       | 8/30    | Linear regression                                       | [Book 1](https://probml.github.io/pml-book/book1.html): 4.2.1, 4.2.2, 11.1-11.2.4           | [Notes](../lecture2-linear-regression/notes.qmd)                                                  |                                                                                                                              |
|         |         |                                                         |                                                                                             |                                                                                                   |                                                                                                                              |
|         |         |                                                         |                                                                                             | [Slides](../lecture2-linear-regression/slides.qmd)                                                |                                                                                                                              |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
|         | 9/4     | No class (Labor day)                                    |                                                                                             |                                                                                                   |                                                                                                                              |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 3       | 9/6     | Logistic regression                                     | [Book 1](https://probml.github.io/pml-book/book1.html): 10.1, 10.2.1, 10.2.3, 10.3.1-10.3.3 | [Notes](../lecture3-logistic-regression/notes.qmd)                                                | Homework 2 assigned ([Github](https://github.com/orgs/CS152-Neural-Networks-Fall-2023/repositories)) **Due: 9/12 11:59pm**   |
|         |         |                                                         |                                                                                             |                                                                                                   |                                                                                                                              |
|         |         |                                                         |                                                                                             | [Slides](../lecture3-logistic-regression/slides.qmd)                                              | [Solutions](../assignments/homework2-linear-regression/solutions.html)                                                       |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 4       | 9/11    | Feature transforms                                      | [Book 1](https://probml.github.io/pml-book/book1.html): 10.2.2                              | [Notes](../lecture4-feature-transforms/notes.qmd)                                                 |                                                                                                                              |
|         |         |                                                         |                                                                                             |                                                                                                   |                                                                                                                              |
|         |         |                                                         |                                                                                             | [Slides](../lecture4-feature-transforms/slides.html)                                              |                                                                                                                              |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 5       | 9/13    | Linear and logistic regression discussion               |                                                                                             |                                                                                                   |                                                                                                                              |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 6       | 9/18    | Linear and logistic regression discussion               |                                                                                             | [Notebook](https://colab.research.google.com/drive/1MlFAWYkgI58xjxTYWKJoSdU64xRObyaq?usp=sharing) |                                                                                                                              |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 7       | 9/20    | Neural networks introduction                            | [Book 1](https://probml.github.io/pml-book/book1.html): 13.1, 13.2                          | [Notes](../lecture5-neural-networks-intro/notes.qmd)                                              | Homework 3 assigned ([Github](https://github.com/orgs/CS152-Neural-Networks-Fall-2023/repositories)) **Due: 9/26 11:59pm**   |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 8       | 9/25    |                                                         |                                                                                             |                                                                                                   |                                                                                                                              |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 9       | 9/27    |                                                         |                                                                                             |                                                                                                   | Homework 4 assigned ([Github](https://github.com/orgs/CS152-Neural-Networks-Fall-2023/repositories)) **Due: 10/3 11:59pm**   |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 10      | 10/2    |                                                         |                                                                                             |                                                                                                   |                                                                                                                              |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 11      | 10/4    |                                                         |                                                                                             |                                                                                                   | Homework 5 assigned ([Github](https://github.com/orgs/CS152-Neural-Networks-Fall-2023/repositories)) **Due: 10/10 11:59pm**  |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 12      | 10/9    |                                                         |                                                                                             |                                                                                                   |                                                                                                                              |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 13      | 10/11   |                                                         |                                                                                             |                                                                                                   | Homework 6 assigned ([Github](https://github.com/orgs/CS152-Neural-Networks-Fall-2023/repositories)) **Due: 10/19 11:59pm**  |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
|         | 10/16   | No class (Fall break)                                   |                                                                                             |                                                                                                   |                                                                                                                              |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 14      | 10/18   |                                                         |                                                                                             |                                                                                                   | Homework 7 assigned ([Github](https://github.com/orgs/CS152-Neural-Networks-Fall-2023/repositories)) **Due: 10/24 11:59pm**  |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 15      | 10/23   |                                                         |                                                                                             |                                                                                                   |                                                                                                                              |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 16      | 10/25   |                                                         |                                                                                             |                                                                                                   | Homework 8 assigned ([Github](https://github.com/orgs/CS152-Neural-Networks-Fall-2023/repositories)) **Due: 9/5 11:59pm**    |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 17      | 10/30   |                                                         |                                                                                             |                                                                                                   |                                                                                                                              |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 18      | 11/1    |                                                         |                                                                                             |                                                                                                   | Homework 9 assigned ([Github](https://github.com/orgs/CS152-Neural-Networks-Fall-2023/repositories)) **Due: 11/7 11:59pm**   |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 19      | 11/6    |                                                         |                                                                                             |                                                                                                   |                                                                                                                              |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
|         | 11/8    |                                                         |                                                                                             |                                                                                                   |                                                                                                                              |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 20      | 11/13   |                                                         |                                                                                             |                                                                                                   |                                                                                                                              |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 21      | 11/15   |                                                         |                                                                                             |                                                                                                   | Homework 10 assigned ([Github](https://github.com/orgs/CS152-Neural-Networks-Fall-2023/repositories)) **Due: 11/20 11:59pm** |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 22      | 11/20   |                                                         |                                                                                             |                                                                                                   |                                                                                                                              |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
|         | 11/22   | No class (Thanksgiving break)                           |                                                                                             |                                                                                                   | Homework 11 assigned ([Github](https://github.com/orgs/CS152-Neural-Networks-Fall-2023/repositories)) **Due: 12/5 11:59pm**  |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 23      | 11/27   |                                                         |                                                                                             |                                                                                                   |                                                                                                                              |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 24      | 11/29   |                                                         |                                                                                             |                                                                                                   |                                                                                                                              |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 25      | 12/5    |                                                         |                                                                                             |                                                                                                   |                                                                                                                              |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 26      | 12/6    |                                                         |                                                                                             |                                                                                                   |                                                                                                                              |
+---------+---------+---------------------------------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+